CREATE TABLE CARS(MODEL TEXT, BRAND TEXT, CLASS TEXT, PRICE INTEGER, CURRENCY TEXT);

INSERT INTO CARS VALUES('LA FERRARI', 'FERRARI', 'A-CLASS', 235000, 'CREDITS');
INSERT INTO CARS VALUES('DART', 'DODGE', 'D-CLASS', 0, 'FREE');
INSERT INTO CARS VALUES('370Z', 'NISSAN', 'D-CLASS', 50000, 'CREDITS');
INSERT INTO CARS VALUES('CONCEPT ONE', 'RIMAC', 'B-CLASS',350000, 'CREDITS');
INSERT INTO CARS VALUES('SURVOLT', 'DS', 'B-CLASS', 45000, 'CREDITS');
INSERT INTO CARS VALUES('CB7', 'FELINO', 'C-CLASS', 250000, 'CREDITS');
INSERT INTO CARS VALUES('SLS ELECTRIC DRIVE', 'MERCEDES', 'C-CLASS', 25000, 'CREDITS');
INSERT INTO CARS VALUES('CB7', 'FELINO', 'B-CLASS', 250000, 'CREDITS');
